import React from 'react';
import { Artifact, AGENTS } from '../types';
import { X, Download, Copy, Terminal } from 'lucide-react';
import { clsx } from 'clsx';

interface SideDrawerProps {
  artifact: Artifact | null;
  isOpen: boolean;
  onClose: () => void;
}

const SideDrawer: React.FC<SideDrawerProps> = ({ artifact, isOpen, onClose }) => {
  if (!artifact) return null;
  const agent = AGENTS[artifact.role];

  const handleCopy = () => {
    navigator.clipboard.writeText(artifact.content);
  };

  const handleDownload = () => {
    const blob = new Blob([artifact.content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = artifact.filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <>
      {/* Backdrop */}
      <div 
        className={clsx(
          "fixed inset-0 bg-black/60 backdrop-blur-sm z-40 transition-opacity duration-300",
          isOpen ? "opacity-100" : "opacity-0 pointer-events-none"
        )}
        onClick={onClose}
      />

      {/* Drawer */}
      <div 
        className={clsx(
          "fixed top-0 right-0 h-full w-full md:w-[600px] lg:w-[800px] bg-[#09090b] border-l border-white/10 z-50 shadow-2xl transform transition-transform duration-300 ease-out flex flex-col",
          isOpen ? "translate-x-0" : "translate-x-full"
        )}
      >
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-white/10 bg-[#09090b]">
          <div className="flex items-center gap-4">
            <div className={clsx("w-10 h-10 rounded-xl flex items-center justify-center bg-white/5", agent.color)}>
              <Terminal size={20} />
            </div>
            <div>
              <h2 className="text-lg font-bold text-white">{artifact.filename}</h2>
              <p className={clsx("text-xs font-medium", agent.color)}>Generated by {agent.name}</p>
            </div>
          </div>
          <button 
            onClick={onClose}
            className="p-2 hover:bg-white/10 rounded-full text-zinc-400 hover:text-white transition-colors"
          >
            <X size={20} />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-8 custom-scrollbar bg-[#09090b]">
          <div className="prose prose-invert max-w-none">
            {/* Simple Markdown Rendering - wrapping in whitespace-pre-wrap to preserve formatting if raw */}
            <div className="whitespace-pre-wrap font-mono text-sm leading-relaxed text-zinc-300">
              {artifact.content}
            </div>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="p-6 border-t border-white/10 bg-[#09090b] flex items-center justify-between">
          <div className="text-xs text-zinc-500 font-mono">
            {artifact.content.length} chars • {artifact.status}
          </div>
          <div className="flex items-center gap-3">
            <button 
              onClick={handleCopy}
              className="flex items-center gap-2 px-4 py-2 bg-white/5 hover:bg-white/10 border border-white/10 rounded-lg text-sm font-medium text-white transition-all"
            >
              <Copy size={16} />
              Copy
            </button>
            <button 
              onClick={handleDownload}
              className="flex items-center gap-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-sm font-medium transition-all shadow-lg shadow-indigo-500/20"
            >
              <Download size={16} />
              Download .md
            </button>
          </div>
        </div>
      </div>
    </>
  );
};

export default SideDrawer;